# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2e423422e4e7b19d76a4885e70e3507d846c3d1b1ea84320c5c39239bab3b93533c20ef232e0bbd0badc8a00d58dc9ae094811d04e511e873a443e75c57111d

test:
  secret_key_base: 3bb3c099711af77290e0cef6938e9cfc265bd41e08d0c7c8f1b49d218745946a7a4a13cc5d73a93a597be6a7bf26e361d80a155193e63c1e3a5fb83fbbd788f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
